version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - demo-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "15432:80"
    networks:
      - demo-network
    restart: unless-stopped

  demo-service:
    image: abhijitk7/tourist-management:demo-service
    ports:
      - 8010:8010
    restart: always
    volumes:
      - demo_service_data:/data/db
    networks:
      - demo-network
    depends_on:
      - postgres


volumes:
  postgres:
  pgadmin:
  demo_service_data:

# Networks to be created to facilitate communication between containers
networks:
  demo-network: