version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - demo-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "15432:80"
    networks:
      - demo-network
    restart: unless-stopped

  quartz-demo-service:
    image: abhijitk7/quartz:quartz-demo-service
    ports:
      - 8084
    environment:
      JAVA_OPTS: >
        -DPG_HOST=postgres
    volumes:
      - quartz-demo-service:/data/db
    restart: always
    depends_on:
      - postgres
    networks:
      - demo-network

volumes:
  postgres:
  pgadmin:
  quartz-demo-service:

# Networks to be created to facilitate communication between containers
networks:
  demo-network: